In [2]:
#QUE 1
import numpy as np
arr=np.array([1,2,3,4,5])

# a addition
add_array=arr+2
print(add_array)

# b multiply by 3
mul_array=arr*3
print(mul_array)

# c Divide every element by 2
div_array=arr/2
print(div_array)


[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [13]:
# QUE 2.a
arr=np.array([1,2,3,6,4,5])
print(arr)

reverse_array=arr[::-1]             # or reverse_array[:-7:-1]
print(reverse_array)

[1 2 3 6 4 5]
[5 4 6 3 2 1]


In [17]:
#QUE 2.b
x = np.array([1,2,3,4,5,1,2,1,1,1])

unique, counts = np.unique(x, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]

indices = np.where(x == most_frequent_value)[0]

print("Most frequent value in x:", most_frequent_value)
print("Indices:", indices)


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

unique, counts = np.unique(y, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]

indices = np.where(y == most_frequent_value)[0]

print("Most frequent value in y:", most_frequent_value)
print("Indices:", indices)

Most frequent value in x: 1
Indices: [0 5 7 8 9]
Most frequent value in y: 1
Indices: [0 1 2]


In [27]:
#QUE 3
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
#3.a
print(arr[0,1])             #or print(arr[0][1])

#3.b
print(arr[2,0]) 

20
70


In [32]:
# QUE 4
jahid=np.linspace(10,100,25)
print(jahid)

print("Dimensions of the array:", jahid.ndim)
print("Shape of the array:", jahid.shape)
print("Total elements in the array:", jahid.size)
print("Data type of each element:", jahid.dtype)
print("Total number of bytes consumed by the array:", jahid.nbytes)

transposed_array_reshape = jahid.reshape(25, 1)
print("Transposed array using reshape():\n", transposed_array_reshape)

transposed_array_T = jahid.T
print("Transposed array using T attribute:\n", transposed_array_T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total elements in the array: 25
Data type of each element: float64
Total number of bytes consumed by the array: 200
Transposed array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [33]:
# QUE 5
ucs420_jahid=np.array([[10, 20, 30, 40],[50, 60, 70, 80],[90, 15, 20, 35]])
mean = np.mean(ucs420_jahid)
median = np.median(ucs420_jahid)
max = np.max(ucs420_jahid)
min = np.min(ucs420_jahid)
unique= np.unique(ucs420_jahid)

print("Mean:", mean)
print("Median:", median)
print("Max:", max)
print("Min:", min)
print("Unique elements:", unique)

reshaped_ucs420_jahid = ucs420_jahid.reshape(4, 3)
print("Reshaped array (4 rows, 3 columns):\n", reshaped_ucs420_jahid)

resized_ucs420_jahid = np.resize(ucs420_jahid, (2, 3))
print("Resized array (2 rows, 3 columns):\n", resized_ucs420_jahid)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array (4 rows, 3 columns):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array (2 rows, 3 columns):
 [[10 20 30]
 [40 50 60]]
