QUE 1 For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), Find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [9]:
import numpy as np
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(gfg)
print(gfg.sum())
row_sum=np.sum(gfg,axis=1)
print(row_sum)
column_sum=np.sum(gfg,axis=0)
print(column_sum)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
45
[[14]
 [16]
 [15]]
[[20  9 16]]


Q.2 (a)For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements


In [11]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_elements = np.sort(array)[:4]
largest_elements = np.sort(array)[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", smallest_elements)
print("5 largest elements:", largest_elements)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only

In [12]:
import numpy as np
array=np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer=array[np.floor(array)==array]
float_ele=array[np.floor(array)!=array]
print(integer)
print(float_ele)

[1. 2. 3. 2.]
[1.2 2.2]
